version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=swkom
    ports:
      - '5432:5432'
    restart: always